/* Generated by generate_config.py; do not edit protocol constants here. */
const KACHI_CONFIG = Object.freeze({
  "USB_VID": 4617,
  "USB_PID": 50525,
  "USB_PRODUCT": "Kachi Button",
  "USB_MANUFACTURER": "HAPT Lab, LLC",
  "USB_MANUFACTURERS": [
    "HAPT Lab, LLC",
    "CreatorKanata"
  ],
  "MAX_TEXT_LENGTH": 32,
  "MAX_REPEAT": 99,
  "MAX_INTERVAL_MS": 60000,
  "BOOT_COMMAND_MAGIC": 19266,
  "BOOT_STATUS_REQUEST": 90,
  "CONFIG_INFO_REQUEST": 96,
  "CONFIG_GET_REQUEST": 97,
  "CONFIG_BEGIN_REQUEST": 98,
  "CONFIG_BYTE_REQUEST": 99,
  "CONFIG_APPLY_REQUEST": 100,
  "CONFIG_SAVE_REQUEST": 101,
  "CHIP_ID_REQUEST": 102,
  "KEY_COUNT": 3,
  "SAVE_TIMEOUT_MS": 5000,
  "SAVE_POLL_MS": 20
});
