"""Generate browser protocol constants from the firmware's single source of truth."""
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "firmware"))
import config


def javascript():
    names = ('USB_VID', 'USB_PID', 'USB_PRODUCT', 'USB_MANUFACTURER', 'USB_MANUFACTURERS', 'MAX_TEXT_LENGTH',
             'MAX_REPEAT', 'MAX_INTERVAL_MS', 'BOOT_COMMAND_MAGIC', 'BOOT_STATUS_REQUEST',
             'CONFIG_INFO_REQUEST', 'CONFIG_GET_REQUEST', 'CONFIG_BEGIN_REQUEST',
             'CONFIG_BYTE_REQUEST', 'CONFIG_APPLY_REQUEST', 'CONFIG_SAVE_REQUEST', 'CHIP_ID_REQUEST')
    values = {name: getattr(config, name) for name in names}
    values.update(KEY_COUNT=len(config.PINS), SAVE_TIMEOUT_MS=config.WEB_SAVE_TIMEOUT_MS,
                  SAVE_POLL_MS=config.WEB_SAVE_POLL_MS)
    return ('/* Generated by generate_config.py; do not edit protocol constants here. */\n'
            'const KACHI_CONFIG = Object.freeze(' + json.dumps(values, indent=2) + ');\n')


if __name__ == '__main__':
    Path(__file__).with_name('config.js').write_text(javascript())
